### ISSUE TITLE
Update bbolt version to go.etcd.io/bbolt

### ISSUE THREAD

**Issue by zhaojizhuang** [br0xen/boltbrowser#61]
panic when browser containerd 1.17.1‘s metadata

```shell
panic: runtime error: index out of range [18446744073709547520] with length 281474976710655

goroutine 1 [running]:
github.com/boltdb/bolt.(*DB).page(...)
	/data00/code/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:796
github.com/boltdb/bolt.Open({0x7ffd572e0544, 0x3a}, 0x48690?, 0xc00008de60)
	/data00/code/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:237 +0x545
main.main()
	/data00/code/pkg/mod/github.com/br0xen/boltbrowser@v0.0.0-20230515124937-7a5543df994e/main.go:117 +0x1bc
root@n37-006-180:~# boltbrowser /var/lib/containerd/io.containerd.metadata.v1.bolt/meta.db
panic: runtime error: index out of range [18446744073709547520] with length 281474976710655

goroutine 1 [running]:
github.com/boltdb/bolt.(*DB).page(...)
	/data00/code/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:796
github.com/boltdb/bolt.Open({0x7ffc1e7f2544, 0x3a}, 0x48690?, 0xc000059e60)
	/data00/code/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:237 +0x545
main.main()
	/data00/code/pkg/mod/github.com/br0xen/boltbrowser@v0.0.0-20230515124937-7a5543df994e/main.go:117 +0x1bc
```
Maybe we should update bolt version

Due to:
- Since https://github.com/boltdb/bolt has been archived from 2019.3.9，and `boltdb/bolt` is no longer maintained.
- https://github.com/etcd-io/bbolt is still under maintenance, which is a fork for `boltdb/bolt@1.3.1`

**Comment by zhaojizhuang** [comment]
cc @br0xen
